### PR TITLE
Fix writing content standards

### LINKED ISSUE #510: Fix writing content information
## Description

The 'Writing content' section of the Design System is missing some of the guidance used internally.

## Links and resources

> - [Read this post and linked research about plain English](https://gds.blog.gov.uk/2014/02/17/guest-post-clarity-is-king-the-evidence-that-reveals-the-desperate-need-to-re-think-the-way-we-write/) on the Government Digital Service blog.

> - [Research](http://works.bepress.com/cgi/viewcontent.cgi?article=1000&context=christopher_trudeau) shows 80% of lawyers prefer plain English. For example, 97% preferred ‘among other things’ over the more traditional Latin phrase ‘inter alia’.

> - [Read why we aim for 9](http://contentdesign.london/reading/specifying-a-reading-age-for-web-content/).

### PR DESCRIPTION
**Pull request by kelliedesigner**
Closes #510

### CODE REVIEW

File: src/pages/maintenance.js [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+import Paragraph from "../components/Paragraph";
+import Title from "../components/Title";
+import Main from "../components/Main";
+import Content from "../components/Content";
+import Topic from "../components/Topic";
+
+const Page = () => (
+  <DesignSystemLayout>
+    <Helmet>
+      <title>{`Style`}</title>
```
Comment (jeddy3) [inline src/pages/maintenance.js]: Mismatched title.

File: src/pages/voice-and-tone.js [hunk 2]
```diff
@@ -0,0 +1,79 @@
...
+import Paragraph from "../components/Paragraph";
+import Title from "../components/Title";
+import Main from "../components/Main";
+import Content from "../components/Content";
+import Topic from "../components/Topic";
+
+const Page = () => (
+  <DesignSystemLayout>
+    <Helmet>
+      <title>{`Style`}</title>
```
Comment (jeddy3) [inline src/pages/voice-and-tone.js]: Mismatched title.
