### PR TITLE
Fix colour explanation

### LINKED ISSUE #210: Fix explanation of avoiding relying on just colour
## Description

The last rule in the Colour section of the Design System reads 'avoid relying on just colour'.

This isn't clear on what it is referring to.

### PR DESCRIPTION
**Pull request by kelliedesigner**
Closes #210

### CODE REVIEW

File: src/pages/guidance/colour.js [hunk 1]
```diff
@@ -42,7 +42,8 @@ const Pages = () => (
         <Link href="https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html">{`accessible`}</Link>
         {` colour combinations for text`}
       </ListItem>
-      <ListItem>{`avoid relying on just colour`}</ListItem>
+      <ListItem
+      >{`avoid relying on just colour when conveying important information`}</ListItem>
```
Comment (jeddy3) [inline src/pages/guidance/colour.js]: How's about "avoid relying on colour to convey important information"?
