### PR TITLE
Fix differentiation between AttentionGrabbingLink and SubmitAction

### LINKED ISSUE #58: Fix lack of differentiation between SubmitActions and AttentionGrabbingLinks
When demoing the DS it came to light that the differentiation between SubmitActions and AttentionGrabbingLinks isn't clear. And the relationship between Links and  AttentionGrabbingLinks was also not clear.

Original issues:

- #33 
- #44

### PR DESCRIPTION
**Pull request by kelliewellingtons**
Additionally, add underline in all states of interaction, to adhere to usability findings.

Closes #58

### CODE REVIEW

File: src/pages/components.js [hunk 1]
```diff
@@ -28,25 +28,46 @@ const Pages = () => (
       <UnorderedList>
         <ListItem>{`be used for linking to resources`}</ListItem>
         <ListItem>{`be used sparingly`}</ListItem>
-        <ListItem>{`use a verb for example "Download"`}</ListItem>
+        <ListItem>{`use a verb for example "Donate"`}</ListItem>
```
Comment (sl33p) [inline src/pages/components.js]: should there be a comma before for 
> use a verb, for example "Donate"
