### PR TITLE
Fix title props

### LINKED ISSUE #674: Fix title props
Title props could be changed to heading to make it more consistent and less confusing.

### PR DESCRIPTION
**Pull request by kelliedesigner**
Closes #674

### CODE REVIEW

File: src/components/Header/index.js [hunk 1]
```diff
@@ -22,7 +27,7 @@ const Header = ({ href = "/", menu, search, title = "Go to the homepage" }) => {
   return (
     <header className="Header">
       <div className="Header-actions">
-        <a className="Header-logoLink" href={href} title={title}>
+        <a className="Header-logoLink" href={href} heading={heading}>
```
Comment (jeddy3) [inline src/components/Header/index.js]: This needs to stay as `title` as it's an html attribute.
